### ISSUE TITLE
Changes in a root directory cause crash (Access violation)

### ISSUE THREAD

**Issue by PetrP9** [FFMG/myoddweb.directorywatcher#16]
This code replicates the problem:
`Watcher watch= new Watcher();`
`watch.Add(new Request(@"C:\", true));`
`watch.Start();`

When I make changes in the C:\ directory, the application randomly crash. The fastest way to replicate the problem is renaming some folder in the root directory. Usually it takes some time. Sometimes it needs 50 or more renames.
I tried it on two different computers and crashed on both.

Please take a look at it

**Comment by FFMG** [comment]
Hi, 
This was fixed in the develop branch, I am running a couple of tests on my side and I will release the update
Thanks for reporting it.

**Comment by FFMG** [comment]
Hi, 

This issue was fixed in 0.1.9.
Please let me know if you are still having issues, (please open a new ticket if you are having a new issue)

Thanks

**Comment by PetrP9** [comment]
Hi,

It looks like it works fine now

Thank you!
