### ISSUE TITLE
Exception when running Store Packaged version

### ISSUE THREAD

**Issue by milos12345** [FFMG/myoddweb.directorywatcher#3]
My solution has standard WPF project and also Windows Application Packaging Project that packs it for the Microsoft Store. The WPF project runs fine, but when I try to run Store packaged version of the same project there is an exception on the line
`watcher = new Watcher();`

> System.AggregateException
>   HResult=0x80131500
>   Message=One or more errors occurred.
>   Source=MyOddWeb.DirectoryWatcher
>   StackTrace:
>    at myoddweb.directorywatcher.utils.WatcherManager.CreateWatcherFromFileSystem()
>    at myoddweb.directorywatcher.Watcher..ctor()
>    at myclass.cs:line 39 ( watcher = new Watcher(); )
>    
> 
> Inner Exception 1:
> TargetInvocationException: Exception has been thrown by the target of an invocation.
> 
> Inner Exception 2:
> SEHException: External component has thrown an exception.

The packaging project was originally added with New Project > Windows Universal > Windows Application Packaging Project

**Comment by FFMG** [comment]
Hum ... I am not that familiar with WPF and _Windows Application Packaging Project_, again, it would be a lot easier with some sort of sample app so I can reproduce it.

Are you on VS2019? What .NET version are you targeting?

I will try and set something up, but my first guess would be some sort of permission/security issue.

**Comment by milos12345** [comment]
I have tried to make a sample project in VS2017 targeting 4.6.1 but it ran without issues, and the project that failed yesterday also works this PC. Not sure yet, but the difference is this PC has VS2019. I'll try installing VS2019 on the other PC to see if that is the reason

**Comment by milos12345** [comment]
Installed VS2019 on the PC where it did not work. After installing Desktop Development with C++ it would still fail, but after installing .NET Desktop Development it works. All testing was done with VS2017, so I don't know why installing these packages for VS2019 would break or fix is for VS2017. So far everything works.

**Comment by FFMG** [comment]
Hum, thanks for the feedback ... I am still cleaning some code and running some tests to do a non-alpha release sometime next week.

I wills still spend a little bit of time to test WPF as I think it is a worthwhile exercise anyway. I might just add it as a sample app, (in the sample folder).

**Comment by milos12345** [comment]
Thank you for all the hard work and I will keep you updated on any issues I encounter. I am sorry I forgot to send you the link to my WPF and Store Packaging project versions that I used for testing. https://github.com/milos12345/Directorywatcher-WPF-test
