### ISSUE TITLE
Crashing with Access violation 

### ISSUE THREAD

**Issue by milos12345** [FFMG/myoddweb.directorywatcher#6]
I have been running program with 0.1.6-Alpha2 for a few days without issues, and today I have updated nuget package to 0.1.6 stable and after changing folder a few times the program just exits with 'Access violation'

> The program 'X.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

There is no breakpoint, program just closes in debugging mode so I don't know where it breaks, and no stack trace. 
I restored previous project version, it ran without issues, and again, right after the nuget update I'd start getting this program crashes with the same message.
Not sure if it is relevant, but what I am doing differently than your examples is that I am monitoring each folder individually wihout recursion, so I am monitoring the same folder with two watchers (two user controls that handle their own folder content listing and monitor). Can that be an issue, or is there something else?
One of the updates before the 0.1.6-alpha2 had the same issue, but then I was not sure that directorywatcher was causing it so I did not report.

**Comment by milos12345** [comment]
Update: It crashes even when I disable watcher in the second panel. So there are no two watchers that monitor the same directory.

**Comment by milos12345** [comment]
Update2: It crashes on `watcher.Stop();`. I have placed the breakpoint on `watcher.Stop();` and I change folder which calls `Stop();`, press F10 to stop over, and F5 to continue. After 3-6 times repeating this it will crash after stepping over that line.

**Comment by FFMG** [comment]
Hi, 

Can you please try 

`update-package MyOddWeb.DirectoryWatcher -Version 0.1.7-alpha1`

I think it addresses the crash issue although I have not been able to reproduce the exact same scenario.

Thanks

**Comment by FFMG** [comment]
I think this was fixed in 0.1.7, as mentioned, very hard to test without a proper sample.
