### ISSUE TITLE
Strong Name Signing

### ISSUE THREAD

**Issue by Jeko1983** [FFMG/myoddweb.directorywatcher#9]
Hi,

Is it possible for you to sign the assemblies with a strong name? That would be very helpful for my project!

Thank you in advance.

**Comment by FFMG** [comment]
You mean [to verify the code](https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md)?

I am busy with the next release, but I will take a look into it.

**Comment by Jeko1983** [comment]
Yes, that's correct. See also [Sign an assembly with a strong name](https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name).

**Comment by FFMG** [comment]
SN was added to version 0.1.8
